version: '3.3'
services:
  psql:
    container_name: postgres
    image: postgres
    volumes:
      - pgdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=master
      - POSTGRES_PASSWORD=pw
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - "12345:5432"

volumes:
  pgdb: