server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authorization
    username: root
    password: 1234

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework.security: trace
    com.zaxxer.hikari: TRACE
    com.zaxxer.hikari.HikariConfig: DEBUG