server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:12345/test
    driverClassName: org.postgresql.Driver
    username: master
    password: pw

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true