### grant_type = password
POST http://localhost:8081/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=youngbin&password=1234&client_id=clientid&client_secret=secret

### grant_type = custom_credentials
POST http://localhost:8081/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=custom_credentials&custom_code=12345&client_id=clientid&client_secret=secret